zookeeper:
  image: wurstmeister/zookeeper
  ports:
      - "2181:2181"
kafka:
  build: .
  ports:
      - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

manager:
    ports:
        - "9000:9000"
    environment:
          ZK_HOSTS: "zk:2181"
    image: sheepkiller/kafka-manager
    links:
         - zookeeper:zk
